name: to_done
description: Simple To done

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  path:
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
